### ISSUE TITLE
Notifications FAQ Is Outdated

### ISSUE THREAD

**Issue by toxalot** [fetlife/help#34]
FAQ for [How do @ notifications work?](https://github.com/fetlife/help/blob/master/07_tech-support/09_how-do-notifications-work.md) says there are no notifications for @mentions.

**Comment by ThatElfGuy** [comment]
Thanks @toxalot Updating in https://github.com/fetlife/help/pull/36

**Comment by nielsenramon** [comment]
Took us a while but we fixed it! Sorry for the wait :-/
