### ISSUE TITLE
Supported Browsers

### ISSUE THREAD

**Issue by DerangedMind** [fetlife/help#4]
Our supported browsers are listed here: https://github.com/fetlife/help/blob/master/07_tech-support/07_supported-browsers.md

However, we have a few articles that discuss workarounds for old, unsupported browsers:

https://github.com/fetlife/help/blob/master/07_tech-support/06_ie-8-compatability-issue-with-friends-request.md
https://github.com/fetlife/help/blob/master/07_tech-support/05_ie-9-webroot-antivirus-incompatability.md

I feel that we should remove these from our help guidelines if we do not support them.

**Comment by ThatElfGuy** [comment]
Those pages no longer exist - going to close this issue.
